######################################################################
# Automatically generated by qmake (3.0) ?? ????? 1 17:51:23 2014
######################################################################

TEMPLATE = app
TARGET = go
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += MainWindow.h
SOURCES += main.cpp MainWindow.cpp
