######################################################################
# Automatically generated by qmake (3.0) ?? ????? 1 17:51:23 2014
######################################################################

TEMPLATE = app
TARGET = go
INCLUDEPATH += .
QT += widgets gui network

# Input
HEADERS += MainWindow.h FieldDraw.h NetWork.h
SOURCES += main.cpp MainWindow.cpp FieldDraw.cpp NetWork.cpp
